Repository ca45382/shioriBotDotNet, pull requests merged in 2021-07, with the labels that each got.

#90 Brotli.netを廃止し、SystemのCompressionを導入
  PriconneBotConsoleApp.csproj
  Script/Boot/BotInitialize.cs
Labels: bug

#87 Refactor/#86
  Database/Redive/RediveCampaignLoader.cs
  Database/Shiori/DatabaseClanDataController.cs
  Database/Shiori/DatabaseConnector.cs
  Database/Shiori/DatabaseDeclarationController.cs
  Database/Shiori/DatabaseFeatureController.cs
  Database/Shiori/DatabaseMessageDataController.cs
  Database/Shiori/DatabasePlayerDataController.cs
  Database/Shiori/DatabaseReservationController.cs
  Database/Shiori/DatabaseServerDataController.cs
  Database/Shiori/DatabaseTaskKillController.cs
  Extension/StringExtension.cs
  Script/BaseClass.cs
  Script/Boot/BotInitialize.cs
  Script/Boot/DiscordDataLoader.cs
  Script/ClanBattle/BattleDeclaration.cs
  Script/ClanBattle/BattleReservation.cs
  Script/ClanBattle/BattleTaskKill.cs
  Script/Program.cs
  Script/ReceiveMessageController.cs
  Script/ReceiveReactionController.cs
  Script/Utility/PriconneEventViewer.cs
  Script/Utility/TimeLineConversion.cs
Labels: 改善

#92 [fix] 不要なコロンを削除
  Script/Program.cs
Labels: bug

#91 凸報告の作成
  DataModel/AttackType.cs
  DataModel/Shiori/PlayerData.cs
  DataModel/Shiori/ReportData.cs
  DataType/AttackType.cs
  DataType/ErrorType.cs
  DataType/InfomationType.cs
  Database/Shiori/DatabaseConnector.cs
  Database/Shiori/DatabasePlayerDataController.cs
  Database/Shiori/DatabaseReportDataController.cs
  Define/Common.cs
  Extension/EnumExtension.cs
  Script/ClanBattle/BattleReport.cs
  Script/ReceiveMessageController.cs
  Script/Utility/ConversionAttackNumber.cs
  Script/Utility/EnumMapper.cs
Labels: 新機能

#100 持ち越し登録機能の作成
  DataModel/Shiori/CarryOverData.cs
  DataModel/Shiori/PlayerData.cs
  Database/Shiori/DatabaseCarryOverController.cs
  Database/Shiori/DatabaseConnector.cs
  Define/Common.cs
  PriconneBotConsoleApp.csproj
  Script/ClanBattle/BattleCarryOver.cs
  Script/ReceiveMessageController.cs
Labels: 新機能

#113 持ち越し表記に"持"を追加
  Script/Utility/ConversionAttackNumber.cs
Labels: 改善

#112 !rmで他人の持ち越し削除を追加
  Script/ClanBattle/BattleCarryOver.cs
Labels: 新機能

#104 進行チャンネルの実装
  DataModel/AttackType.cs
  DataModel/Shiori/ClanData/MessageData.cs
  DataModel/Shiori/PlayerData.cs
  DataModel/Shiori/ProgressData.cs
  DataType/ProgressStatus.cs
  Database/Shiori/DatabaseConnector.cs
  Database/Shiori/DatabaseProgressController.cs
  Database/Shiori/DatabaseReportDataController.cs
  Define/CommonDefine.cs
  Extension/StringExtension.cs
  Script/ClanBattle/BattleProgress.cs
  Script/ReceiveMessageController.cs
  Script/Utility/ConversionAttackNumber.cs
  Script/Utility/EnumMapper.cs
Labels: 新機能

#115 予約一覧でのInteractionを有効にする
  Script/ClanBattle/BattleReservation.cs
  Script/ReceiveInteractionController.cs
Labels: bug

#117 EnumMapperの改善
  Attribute/Description.cs
  DataType/AttackType.cs
  DataType/ButtonType.cs
  Extension/DictionaryExtension.cs
  Extension/EnumExtension.cs
  Script/ClanBattle/BattleCarryOver.cs
  Script/ClanBattle/BattleDeclaration.cs
  Script/ClanBattle/BattleProgress.cs
  Script/ClanBattle/BattleReport.cs
  Script/ClanBattle/BattleReservation.cs
  Script/ClanBattle/BattleTaskKill.cs
  Script/Utility/ConversionAttackNumber.cs
  Script/Utility/EnumMapper.cs
Labels: 改善

#119 5時更新時にInvalidOperationExceptionが出る問題
  Script/ClanBattle/BattleTaskKill.cs
  Script/ClanBattle/UpdateDate.cs
  Script/Utility/EnumMapper.cs
Labels: bug, 助けて

#122 凸報告でInvalidOperation出ている箇所を修正
  Script/ClanBattle/BattleReport.cs
Labels: bug

#118 メッセージ内容がないときにOutOfRangeが発生する問題を修正
  Script/Utility/Dice.cs
Labels: bug

#109 時限付きメッセージを拡張メソッドとして追加
  Define/TimeDefine.cs
  Extension/ISocketMessageChannelExtension.cs
  Script/ClanBattle/BattleReport.cs
Labels: 改善

#121 BotのConfigデータを読み出す部分を改善
  DataModel/BotConfigData.cs
  Database/Shiori/DatabaseConnector.cs
  PriconneBotConsoleApp.csproj
  Script/Boot/JsonDataManager.cs
  Script/Program.cs
Labels: 改善

#127 JetBrains Riderが自動生成するファイルをIgnoreしたい
  .gitignore
Labels: 改善

#126 進行チャンネルのテキスト生成をリファクタリング
  Script/ClanBattle/BattleProgress.cs
Labels: 改善
