Repository ca45382/shioriBotDotNet, pull requests merged in 2021-05, with the labels that each got.

#32 Fix/#21
  Script/BattleReservation.cs
Labels: enhancement

#35 TL変換機能の実装
  Script/ReceiveMessageController.cs
  Script/TimeLineConversion.cs
Labels: 新機能

#33 リアクションを受け取ったときの動作を修正
  Script/Program.cs
  Script/ReceiveReactionController.cs
Labels: bug

#41 Resolve #40
  PriconneBotConsoleApp.csproj
  Script/BattleReservation.cs
Labels: 新機能

#42 ID系をulongに対応
  DataTypes/BotDatabase.cs
  DataTypes/ClanData.cs
  DataTypes/DeclarationData.cs
  DataTypes/PlayerData.cs
  DataTypes/ReservationData.cs
  DataTypes/ServerData.cs
  MySQL/MySQLClanDataController.cs
  MySQL/MySQLConnector.cs
  MySQL/MySQLDeclarationController.cs
  MySQL/MySQLPlayerDataController.cs
  MySQL/MySQLReservationController.cs
  Script/BattleDeclaration.cs
  Script/BattleReservation.cs
  Script/PlayerDataLoader.cs
  Script/ReceiveMessageController.cs
  Script/ReceiveReactionController.cs
Labels: 改善

#44 構文修正
  Script/BattleDeclaration.cs
Labels: 改善

#45 宣言部分のrefactor
  MySQL/MySQLDeclarationController.cs
Labels: 改善

#49 エラーメッセージのenum化
  Script/BattleReservation.cs
  Script/ErrorType.cs
Labels: 改善

#50 現在のボス以外の宣言スタンプは反応しないように対処
  Script/BattleDeclaration.cs
Labels: bug

#52 更新ボタンを追加
  Script/BaseClass.cs
  Script/BattleDeclaration.cs
  Script/BattleReservation.cs
  Script/ReceiveReactionController.cs
Labels: 新機能

#55 Feature/initializer
  DataTypes/RediveVersionData.cs
  PriconneBotConsoleApp.csproj
  Script/BotInitialize.cs
  Script/Program.cs
Labels: 新機能
